<h1>NumPy</h2>

In [2]:
import numpy as np

<h2>The Basics</h2>

In [3]:
a = np.array([3,4,5])
print(a)

[3 4 5]


In [7]:
b = np.array([[4.2, 3.4, 5.4], [3.2, 6.5, 7.8]])
print(b)

[[4.2 3.4 5.4]
 [3.2 6.5 7.8]]
