<h1>NumPy</h2>

In [1]:
import numpy as np

<h2>The Basics</h2>

In [2]:
a = np.array([3,4,5])
print(a)

[3 4 5]


In [3]:
b = np.array([[4.2, 3.4, 5.4], [3.2, 6.5, 7.8]])
print(b)

[[4.2 3.4 5.4]
 [3.2 6.5 7.8]]


In [14]:
## Get Dimension
#a.ndim
b.ndim

2

In [15]:
## Get Shape Ex.: 2x3 
#a.shape
b.shape


(2, 3)

In [17]:
## Get Type
#a.dtype
b.dtype

dtype('float64')

In [21]:
## Get item size (bytes)
a.itemsize

4

In [23]:
## Get total size
#a.size * a.itemsize
#or
a.nbytes

12

<h2>Acessing/Changing specifc elements, rows, columns, etc</h2>

In [25]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [28]:
## Get a specific element [r,c] row, column
a[0,3]

4

In [33]:
## Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [38]:
## Get a specific column
a[: ,4]

array([ 5, 12])

In [47]:
## Getting a Little more fancy [startindex:endindex:stepsize]
a[1, 0:7:2]

array([ 8, 10, 12, 14])

In [52]:
## Change values
#a[0,3] = 999
a[0,3] = 4

<h3>3d example</h3>